### ISSUE TITLE
Schema "migrations"

### ISSUE THREAD

**Issue by dealproc** [Squidex/squidex-identity#1]
I'd like to learn/understand how a project like this would migrate the schema for users, grants, etc. within SquidEx.  Is there something to read to understand this, or guidance that can be provided?

I'm considering using a solution, like SquidEx, for this exact purpose, to enhance the development pipeline we are currently on to relieve the general boilerplate work you have with developing the data storage/retrieval portions of a system.  I need to upgrade our IdentityServer in production, and this looks like a far better fit than trying to develop everything from line 0.

Thoughts/updates would be appreciated.

**Comment by SebastianStehle** [comment]
Sorry, I do not understand the question, What do you mean with "migrating" the schemas?

**Comment by dealproc** [comment]
Well... two fold:

1) From cloning your repository to bringing IdentityServer online, what do I have to do in order to get Squidex to hold the data.
2) As I enhance the product, and want to do new deployments, how are schemas sync'd with what the squidex clients would expect.

**Comment by SebastianStehle** [comment]
Hi,

1. In the apps overview there is an button to create a new app with all needed schemas for you. I also plan to integrate these templates into the new CLI that I am building at the moment, so that you can add the schemas to an existing app.

2. So far it has never happened. But there are several solutions for it:
* It could just be manual work.
* The CLI could run the necessary schema migrations.
* The IdentityServer could run the necessary migrations.

**Comment by dealproc** [comment]
As I am new to Squidex, is this something when I launch the main Squidex console, I will see?

**Comment by SebastianStehle** [comment]
It is just at the start screen at the bottom right:

![screencapture-cloud-squidex-io-app-2018-12-19-22_46_27](https://user-images.githubusercontent.com/1236435/50250023-03a1be00-03e0-11e9-9fce-78c134e41802.png)
